/* GENERATED by tools/gen_model_blob.py — model.onnx (gliner-small-pii-onnx-int8,
 * sha256 2ac41b218b8a87aaf06222fe6431e04b7b2cccb1acc41d1009696ce455014ef7) embedded as raw bytes.
 * blinkwrite-ai/gliner-small-pii-onnx-int8 is Apache-2.0 (base vicgalle/gliner-small-pii). */
#ifndef PII_MODEL_H
#define PII_MODEL_H
#include "pii_model_part00.h"
#include "pii_model_part01.h"
#include "pii_model_part02.h"
#include "pii_model_part03.h"
#include "pii_model_part04.h"
#include "pii_model_part05.h"
#include "pii_model_part06.h"
#include "pii_model_part07.h"
#include "pii_model_part08.h"
#include "pii_model_part09.h"
#include "pii_model_part10.h"
#include "pii_model_part11.h"

typedef struct { const unsigned char *data; unsigned int len; } pii_blob_part;
static const pii_blob_part pii_model_parts[] = {
  { pii_model_part00, 16777216u },
  { pii_model_part01, 16777216u },
  { pii_model_part02, 16777216u },
  { pii_model_part03, 16777216u },
  { pii_model_part04, 16777216u },
  { pii_model_part05, 16777216u },
  { pii_model_part06, 16777216u },
  { pii_model_part07, 16777216u },
  { pii_model_part08, 16777216u },
  { pii_model_part09, 16777216u },
  { pii_model_part10, 16777216u },
  { pii_model_part11, 12229606u },
};
#define PII_MODEL_PARTS 12
#define PII_MODEL_SIZE 196778982u
#define PII_MODEL_SHA256 "2ac41b218b8a87aaf06222fe6431e04b7b2cccb1acc41d1009696ce455014ef7"
#endif
