#!/usr/bin/env python3
"""Generate piirate/include/pii_model_partNN.h — the model.onnx weights as raw
bytes in C source (requirement: model embedded as raw bytes in .c/.h).
Each emitted part is a C string literal (\\xNN escapes); parts stay under the
git 100MB-per-file ceiling. Run from the piirate/ project root with model.onnx in cwd; writes include/.
Deterministic."""
import os, sys, hashlib

SRC = "model.onnx"
PER_PART_SRC_BYTES = 16 * 1024 * 1024          # ~16 MiB raw → ~64 MiB source per part
OUTDIR = "include"

data = open(SRC, "rb").read()
sha = hashlib.sha256(data).hexdigest()
n = len(data)
nparts = (n + PER_PART_SRC_BYTES - 1) // PER_PART_SRC_BYTES
names = []
for idx in range(nparts):
    chunk = data[idx * PER_PART_SRC_BYTES : (idx + 1) * PER_PART_SRC_BYTES]
    sym = "pii_model_part%02d" % idx
    names.append((sym, len(chunk)))
    fn = os.path.join(OUTDIR, "%s.h" % sym)
    with open(fn, "w") as f:
        f.write("/* GENERATED by tools/gen_model_blob.py — model.onnx bytes, part %d/%d.\n"
                " * blinkwrite-ai/gliner-small-pii-onnx-int8 (Apache-2.0). Do not edit. */\n"
                % (idx, nparts))
        f.write("#ifndef PII_MODEL_PART%02d_H\n#define PII_MODEL_PART%02d_H\n" % (idx, idx))
        f.write("static const unsigned char %s[] =\n" % sym)
        STEP = 16384
        for i in range(0, len(chunk), STEP):
            seg = chunk[i:i+STEP]
            f.write('"' + "".join("\\x%02x" % b for b in seg) + '"\n')
        f.write(";\n#endif\n")
    print("wrote", fn, len(chunk), "bytes raw")

with open(os.path.join(OUTDIR, "piirate_model.h"), "w") as f:
    f.write("/* GENERATED by tools/gen_model_blob.py — model.onnx (gliner-small-pii-onnx-int8,\n")
    f.write(" * sha256 %s) embedded as raw bytes.\n" % sha)
    f.write(" * blinkwrite-ai/gliner-small-pii-onnx-int8 is Apache-2.0 (base vicgalle/gliner-small-pii). */\n")
    f.write("#ifndef PII_MODEL_H\n#define PII_MODEL_H\n")
    for sym, _ln in names:
        f.write('#include "%s.h"\n' % sym)
    f.write("\ntypedef struct { const unsigned char *data; unsigned int len; } pii_blob_part;\n")
    f.write("static const pii_blob_part pii_model_parts[] = {\n")
    for sym, ln in names:
        f.write("  { %s, %uu },\n" % (sym, ln))
    f.write("};\n#define PII_MODEL_PARTS %d\n#define PII_MODEL_SIZE %uu\n#define PII_MODEL_SHA256 \"%s\"\n#endif\n"
            % (nparts, n, sha))
print("index header wrote; total raw %d bytes, %d parts, sha256 %s" % (n, nparts, sha))
