#!/usr/bin/env python3
"""Generate piirate/include/tok_data.h from tokenizer.json:
   - C arrays: vocab pieces (blob + offsets utf8-lengths) + scores
   - precompiled NFKC charsmap (raw bytes, base64-decoded)
   - stats/constants (n_vocab, unk id, special ids, min/max piece byte length)
Deterministic output; run from the piirate/ project root with tokenizer.json in cwd; writes include/."""
import json, base64, struct, sys

d = json.load(open("tokenizer.json"))
vocab = d["model"]["vocab"]            # list of [piece, score]
unk_id = d["model"]["unk_id"]
charsmap = base64.b64decode(d["normalizer"]["normalizers"][1]["precompiled_charsmap"])

blob = bytearray(); offs = []; lens = []
for piece, score in vocab:
    b = piece.encode("utf-8")
    offs.append(len(blob)); lens.append(len(b)); blob.extend(b)

maxplen = max(lens)
out = open("include/tok_data.h", "w")
out.write("/* GENERATED by tools/gen_tok_data.py from tokenizer.json — do not edit.\n")
out.write(" * blinkwrite-ai/gliner-small-pii-onnx-int8 :: tokenizer tables.\n")
out.write(" * Apache-2.0 (inherited from base model vicgalle/gliner-small-pii). */\n")
out.write("#ifndef PII_TOK_DATA_H\n#define PII_TOK_DATA_H\n\n")
out.write("#define PII_N_VOCAB %d\n" % (len(vocab),))
out.write("#define PII_MAX_PIECE_BYTES %d\n" % maxplen)

out.write("\nstatic const double pii_tok_score[%d] = {\n" % len(vocab))
for i in range(0, len(vocab), 8):
    out.write("  " + ", ".join("%.9g" % float(vocab[j][1]) for j in range(i, min(i+8, len(vocab)))) + ",\n")
out.write("};\n")

out.write("\nstatic const unsigned int pii_tok_off[%d] = {\n" % len(vocab))
for i in range(0, len(vocab), 16):
    out.write("  " + ", ".join(str(offs[j]) for j in range(i, min(i+16, len(vocab)))) + ",\n")
out.write("};\n")
out.write("\nstatic const unsigned char pii_tok_len[%d] = {\n" % len(vocab))
for i in range(0, len(vocab), 24):
    out.write("  " + ", ".join(str(lens[j]) for j in range(i, min(i+24, len(vocab)))) + ",\n")
out.write("};\n")

out.write("\nstatic const unsigned char pii_tok_blob[%d] = {\n" % len(blob))
BL = len(blob)
for i in range(0, BL, 24):
    out.write("  " + ", ".join("%d" % blob[j] for j in range(i, min(i+24, BL))) + ",\n")
out.write("};\n")

out.write("\nstatic const unsigned char pii_charsmap[%d] = {\n" % len(charsmap))
CL = len(charsmap)
for i in range(0, CL, 24):
    out.write("  " + ", ".join("%d" % charsmap[j] for j in range(i, min(i+24, CL))) + ",\n")
out.write("};\n")
# unicode \w range table -> its own small header (also used by piirate.c)
import re as _re
_wr = _re.compile(r"\w", _re.UNICODE)
ranges=[]
in_r=False
for cp in range(0x110000):
    wch=bool(_wr.match(chr(cp)))
    if wch and not in_r: st=cp; in_r=True
    if (not wch) and in_r: ranges.append((st,cp-1)); in_r=False
if in_r: ranges.append((st,0x10FFFF))
rout = open("include/tok_ranges.h","w")
rout.write("/* GENERATED by tools/gen_tok_data.py — exact python-re \\w ranges. */\n")
rout.write("#ifndef PII_TOK_RANGES_H\n#define PII_TOK_RANGES_H\n")
rout.write("#define PII_N_WRANGES %d\n" % len(ranges))
rout.write("static const unsigned int pii_wrange[%d][2] = {\n" % len(ranges))
for a,b in ranges: rout.write("  {%uu, %uu},\n" % (a,b))
rout.write("};\n#endif\n")
rout.close()
out.write("#define PII_CHARSMAP_LEN %d\n\n#endif\n" % CL)
out.close()
print("wrote include/tok_data.h: vocab=%d maxpiece=%d blob=%d charsmap=%d" % (len(vocab), maxplen, BL, CL))
